config/routes.rb
Rails.application.routes.draw do
  
  get 'articles/index'

  resources :articles # only: [:create, :show] or except:

  root 'welcome#index'

   

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true
	validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
  	@articles = Article.all
  end

  #/articles/:id
  def show
    @article = Article.find(params[:id])
  end

  #GET /articles/new
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  #POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
       render :new
    end
  end

  #DELETE /articles/:id
  def destroy
    @article = Article.find(params[:id]).destroy
    redirect_to articles_path
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.haml
- @articles.each do |article|
  %h1= link_to article.title, article
  %div= article.body
  %p= link_to "Eliminar", article, method: :delete   

app/views/articles/new.html.haml
%div.container
  %div.col-xs-6.col-xs-offset-3    
    = render "form", name: "Crear"

    
    

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.body

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse#cuc
  %div.container-fluid
    %div.navbar-header
      %a{ :href => "#", :class => "navbar-brand" } Logo
    %ul.nav.navbar-nav
      %li.active
        =link_to "Home", root_path
      %li 
        =link_to "Articulos", articles_index_path
      %li 
        =link_to "Nuevo", new_article_path
      %li 
        %a{ :href =>"#"} Page 3   

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Blog2
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags 

%div.container-fluid
  %div.row
    = render 'layouts/navbar'
  = yield 

app/views/welcome/index.html.haml
%h1 Welcome to my blog